[package]
name = "transaction_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.17"
bincode = "1.3"
hex = "0.4"
quinn = "0.10"
tokio = { version = "1.0", features = ["full"] }
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rcgen = "0.11"
