[package]
name = "transaction_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.17"
bincode = "1.3"
hex = "0.4"
nix = { version = "0.29.0", features = ["socket"] }
libc = "0.2"
